### ISSUE TITLE
Проблема с приоритетом операторов

### ISSUE THREAD

**Issue by optimistex** [jcubic/expression.php#1]
2+2*2 должно быть равно 6

Решил проблему у себя: 
https://github.com/optimistex/yii2-expression/blob/master/Expression.lib.php#L198-L204

Так же добавил тесты:
https://github.com/optimistex/yii2-expression/blob/master/tests/Expression.php#L272-L300

**Comment by jcubic** [comment]
I've included your fix and tests, I've renamed second test to testVariables.
