### ISSUE TITLE
Implicit multiplication doesn't work anymore

### ISSUE THREAD

**Issue by johnbao6** [jcubic/expression.php#3]
When I  try to run SYNOPSIS (https://github.com/jcubic/expression.php#synopsis)

It shows:

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in C:\Apache24\htdocs\chem\expression.php on line 359

Perhaps needs renew some files.

**Comment by jcubic** [comment]
Thanks for the heads up, I will check it out when I have time.

**Comment by jcubic** [comment]
Can you share what kind of expression you use? Because unit tests don't give any warning. I use `PHP 8.2.10`

**Comment by johnbao6** [comment]
Sorry, it seems above problem was my fault, probably configure problem somewhere, because it disappeared when I tried in another computer.

Meanwhile I have another problem, the multiple * cannot be omitted, i.e. '2(2-1)' cannot be decoded, but '2*(2-1)' is OK;
'2y' is wrong, but '2*y' is OK.

**Comment by jcubic** [comment]
This is how any computer calculator works this is not paper Math `*` is mandatory.

**Comment by johnbao6** [comment]
But it means your example doesn't work. 
[bug](https://github.com/johnbao6/open/blob/master/Screenshot_2023-10-04_09-07-37.png)

**Comment by jcubic** [comment]
Hm, maybe it should work, I need to investigate. See how the original code works.

**Comment by jcubic** [comment]
It seems that implicit multiplication got removed when adding new features.

**Comment by jcubic** [comment]
I've removed implicit multiplication from README.

**Comment by johnbao6** [comment]
Implicit multiplication is somehow useful, should not be removed simply.

**Comment by jcubic** [comment]
Added back the implicit multiplication. I also prepared the code to publish as a package.
