### ISSUE TITLE
New issue with v8.2 of PHP

### ISSUE THREAD

**Issue by backdoorslider** [jcubic/expression.php#5]
In PHP v8.2, line 359 :  `if (preg_match("/^([a-z]\w*)\($/", $stack->last(3)))`      now fails if the stack contains fewer than 3 values

**Comment by jcubic** [comment]
Thanks for the report will check it. Do you have an example expression that fails?

**Comment by backdoorslider** [comment]
Sure, an expression as simple as 2+4 will fail, as there's nothing in the
$stack variable.  This worked in v8.0 but fails in v8.2

Here's the error I received:
An error occurred in script '<...>/Expression.php' on line 359:
preg_match(): Passing null to parameter #2 ($subject) of type string is
deprecated

**Comment by jcubic** [comment]
Great thanks.

**Comment by jcubic** [comment]
Are you sure it's PHP 8.2? I have `8.2.14` and it works fine. GitHub action run on PHP 8.1 updated it to 8.2.

But I've added:

```
error_reporting(E_ALL);
```

and got those but they were deprecation warnings and fixed all of them. Also added this to unit tests.

**Comment by backdoorslider** [comment]
Yes, 8.2.0.

Thanks,
